version: '2.0'
services:
    c:
        restart: always
        image: rettier/c-server
        build: .
        ports:
            - 8099:80
        environment:
            HOST: 0.0.0.0
            PORT: 8099
            STORAGE_BACKEND: file
            STORAGE_PATH: /data
        volumes:
            - ./data:/data


